/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.DangNhapDAO;
import DAO.LichLamViecDAO;
import DTO.INFO_TKNV;
import DTO.lichlamviec;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Le Chuong
 */
public class PFPhanLich extends javax.swing.JPanel {

    /**
     * Creates new form PFPhanLich
     */
    public PFPhanLich() {
        initComponents();
        loadMaNV1();
        loadMaNV2();
        loadMaNV3();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        btnThemTK = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        LamMoi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ngay = new javax.swing.JComboBox<>();
        thang = new javax.swing.JComboBox<>();
        nam = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(992, 499));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Phân lịch");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nhập mã nhân viên");

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ngày", "Ca", "Giờ bắt đầu", "Giờ kết thúc", "Mã NV", "Nhân Viên"
            }
        ));
        jScrollPane1.setViewportView(TableNhanVien);

        btnThemTK.setBackground(new java.awt.Color(102, 102, 255));
        btnThemTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemTK.setText("Thêm lịch");
        btnThemTK.setBorder(null);
        btnThemTK.setBorderPainted(false);
        btnThemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemTK.setFocusPainted(false);
        btnThemTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemTKMouseExited(evt);
            }
        });
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimkiem.setForeground(new java.awt.Color(153, 153, 153));
        txtTimkiem.setText("Nhập mã NV...");
        txtTimkiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimkiemFocusGained(evt);
            }
        });
        txtTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimkiemMouseClicked(evt);
            }
        });
        txtTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimkiemKeyPressed(evt);
            }
        });

        btnTimkiem.setBackground(new java.awt.Color(102, 102, 255));
        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseExited(evt);
            }
        });
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        LamMoi.setBackground(new java.awt.Color(102, 102, 255));
        LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LamMoi.setText("Làm mới");
        LamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LamMoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LamMoiMouseExited(evt);
            }
        });
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Tháng/Năm");

        ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                thangItemStateChanged(evt);
            }
        });

        nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", " " }));
        nam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namItemStateChanged(evt);
            }
        });

        jLabel3.setText("Ngày");

        jLabel4.setText("Ca 1");

        jLabel6.setText("Ca 2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel7.setText("Ca 3");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnTimkiem)
                        .addGap(39, 39, 39)
                        .addComponent(LamMoi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean isLeapYear(int year) {
        return (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
    }
    
    public void getDaysOfMonth(int month,int year) {
        if (month == Month.FEBRUARY.getValue()) {
            // Tháng 2 có thể có 28 hoặc 29 ngày
            ngay.removeAllItems();
            if (isLeapYear(year)){
                for (int i = 1; i <= 29; i++) 
                   ngay.addItem(String.valueOf(i));
            }
            else{
                for (int i = 1; i <= 28; i++) 
                   ngay.addItem(String.valueOf(i));    
            }
        } else if (month == Month.APRIL.getValue() || month == Month.JUNE.getValue() ||
                   month == Month.SEPTEMBER.getValue() || month == Month.NOVEMBER.getValue()) {
            // Các tháng 4, 6, 9, 11 có 30 ngày
            ngay.removeAllItems();
            for (int i = 1; i <= 30; i++) {
                ngay.addItem(String.valueOf(i));   
            }
        } else {
            // Các tháng còn lại có 31 ngày
            ngay.removeAllItems();
            for (int i = 1; i <= 31; i++) {
                ngay.addItem(String.valueOf(i));   
            }
        }
    }
    
    private void loadMaNV1() {
        ArrayList<String> list = LichLamViecDAO.LoadMaNV();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("--Chọn nhân viên--");
        for (String item : list) {
            jComboBox1.addItem(item);
        }
    }
    private void loadMaNV2() {
        ArrayList<String> list = LichLamViecDAO.LoadMaNV();
        jComboBox2.removeAllItems();
        jComboBox2.addItem("--Chọn nhân viên--");
        for (String item : list) {
            jComboBox2.addItem(item);
        }
    }
    private void loadMaNV3() {
        ArrayList<String> list = LichLamViecDAO.LoadMaNV();
        jComboBox3.removeAllItems();
        jComboBox3.addItem("--Chọn nhân viên--");
        for (String item : list) {
            jComboBox3.addItem(item);
        }
    }
    
    public void loadTable() {
        ArrayList<lichlamviec> list = LichLamViecDAO.loadLich();
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNgay();
            row[1] = list.get(i).getTenCa();
            row[2] = list.get(i).getGioBatDau();
            row[3] = list.get(i).getGioKetThuc();
            row[4] = list.get(i).getMaNV();
            row[5] = list.get(i).getTenNV();
            tblModel.addRow(row);
        }
    }
    
    public void loadTable2(String ma) {
        ArrayList<lichlamviec> list = LichLamViecDAO.loadTimKiem(ma);
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNgay();
            row[1] = list.get(i).getTenCa();
            row[2] = list.get(i).getGioBatDau();
            row[3] = list.get(i).getGioKetThuc();
            row[4] = list.get(i).getMaNV();
            row[5] = list.get(i).getTenNV();
            tblModel.addRow(row);
        }
    }
    
    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        
         String ca1 = jComboBox1.getSelectedItem().toString();
         String ca2= jComboBox2.getSelectedItem().toString();
         String ca3 = jComboBox3.getSelectedItem().toString();
         
         if (ca1.equals("--Chọn nhân viên--"))
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên ca 1!");
         else if (ca2.equals("--Chọn nhân viên--")) 
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên ca 2!");
         else if (ca3.equals("--Chọn nhân viên--")) 
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên ca 3!");
         else {
              String Ngay=nam.getSelectedItem().toString()+"-"+thang.getSelectedItem().toString() +"-"+ ngay.getSelectedItem().toString();
              LichLamViecDAO lx=new LichLamViecDAO();
              if (lx.checkngay(Ngay)==true) {
                    if ((lx.themlich(Ngay, "CA_1", ca1) > 0) && (lx.themlich(Ngay, "CA_2", ca2) > 0) && (lx.themlich(Ngay, "CA_3", ca3) > 0)) {
                        JOptionPane.showMessageDialog(this, "Thêm thành công!"); 
                        loadTable();
                    }
                    else {
                         JOptionPane.showMessageDialog(this, "Thêm thất bại!");
                    }
              }
              else {
                  String x=ngay.getSelectedItem().toString()+"-"+thang.getSelectedItem().toString() +"-"+ nam.getSelectedItem().toString();
                  String s="Ngày "+x+" đã được phân!Bạn có muốn cập nhật lại?";
                  // Hiển thị hộp thoại Yes/No và lấy kết quả
                  int choice = JOptionPane.showConfirmDialog(null, s, "Xác nhận", JOptionPane.YES_NO_OPTION);

                  // Kiểm tra kết quả
                  if (choice == JOptionPane.YES_OPTION) {
                    // Người dùng chọn Yes
                        if ((lx.capNhatLich(Ngay, "CA_1", ca1) > 0) && (lx.capNhatLich(Ngay, "CA_2", ca2) > 0) && (lx.capNhatLich(Ngay, "CA_3", ca3) > 0)) {
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");     
                        loadTable();
                    }
                    else {
                         JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
                    }
                  } 
              }
                                                                                
          }
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void txtTimkiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimkiemFocusGained

    }//GEN-LAST:event_txtTimkiemFocusGained

    private void txtTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimkiemMouseClicked
        txtTimkiem.setText("");
        txtTimkiem.setForeground(Color.black);
    }//GEN-LAST:event_txtTimkiemMouseClicked

    private void txtTimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimkiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
            Object[] row = new Object[6];
            String manv = txtTimkiem.getText();
            DangNhapDAO dn = new DangNhapDAO();
            if (txtTimkiem.getText().contains("Nhập mã NV...") == true) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
            } else if (txtTimkiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
                txtTimkiem.setText("Nhập mã NV...");
                txtTimkiem.setForeground(new Color(153, 153, 153));
            } else {
                loadTable2(manv);
            }          
        }
    }//GEN-LAST:event_txtTimkiemKeyPressed

    private void btnTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimkiemMouseClicked

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[6];
        String manv = txtTimkiem.getText();
        DangNhapDAO dn = new DangNhapDAO();
        if (txtTimkiem.getText().contains("Nhập mã NV...") == true) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
        } else if (txtTimkiem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
            txtTimkiem.setText("Nhập mã NV...");
            txtTimkiem.setForeground(new Color(153, 153, 153));
        } else {
                loadTable2(manv);
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void LamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LamMoiMouseClicked

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
        txtTimkiem.setText("Nhập tài khoản...");
        txtTimkiem.setForeground(new Color(153, 153, 153));
        loadTable();
    }//GEN-LAST:event_LamMoiActionPerformed

    private void thangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_thangItemStateChanged
        // TODO add your handling code here:
        int month=Integer.parseInt(thang.getSelectedItem().toString());
        int year= Integer.parseInt(nam.getSelectedItem().toString());
        getDaysOfMonth(month, year);
    }//GEN-LAST:event_thangItemStateChanged

    private void namItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namItemStateChanged
        // TODO add your handling code here:
        int month=Integer.parseInt(thang.getSelectedItem().toString());
        int year= Integer.parseInt(nam.getSelectedItem().toString());
        getDaysOfMonth(month, year);
    }//GEN-LAST:event_namItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
//        if (jComboBox2.getSelectedItem()!=null){
//        
//            String x=jComboBox2.getSelectedItem().toString();
//            if(!x.equals("--Chọn nhân viên--")){
//                loadMaNV1();
//                jComboBox1.removeItem(x);
//                loadMaNV3();
//                jComboBox3.removeItem(x);
//            }
//        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
//        if (jComboBox1.getSelectedItem()!=null){
//        
//            String x=jComboBox1.getSelectedItem().toString();
//            if(!x.equals("--Chọn nhân viên--")){
//                loadMaNV2();
//                jComboBox2.removeItem(x);
//            }
//        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
//         if (jComboBox3.getSelectedItem()!=null){
//        
//            String x=jComboBox3.getSelectedItem().toString();
//            if(!x.equals("--Chọn nhân viên--")){
//                loadMaNV2();
//                jComboBox2.removeItem(x);
//            }
//        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void btnThemTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemTKMouseEntered
        // TODO add your handling code here:
        btnThemTK.setFont(new Font(btnThemTK.getFont().getName(), Font.BOLD, btnThemTK.getFont().getSize()));
        btnThemTK.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnThemTKMouseEntered

    private void btnThemTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemTKMouseExited
        // TODO add your handling code here:
        btnThemTK.setFont(new Font(btnThemTK.getFont().getName(), Font.PLAIN, btnThemTK.getFont().getSize()));
        btnThemTK.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnThemTKMouseExited

    private void btnTimkiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseEntered
        // TODO add your handling code here:
        btnTimkiem.setFont(new Font(btnTimkiem.getFont().getName(), Font.BOLD, btnTimkiem.getFont().getSize()));
        btnTimkiem.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnTimkiemMouseEntered

    private void btnTimkiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseExited
        // TODO add your handling code here:
        btnTimkiem.setFont(new Font(btnTimkiem.getFont().getName(), Font.PLAIN, btnTimkiem.getFont().getSize()));
        btnTimkiem.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnTimkiemMouseExited

    private void LamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseEntered
        // TODO add your handling code here:
        LamMoi.setFont(new Font(LamMoi.getFont().getName(), Font.BOLD, LamMoi.getFont().getSize()));
        LamMoi.setForeground(Color.WHITE);
    }//GEN-LAST:event_LamMoiMouseEntered

    private void LamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseExited
        // TODO add your handling code here:
        LamMoi.setFont(new Font(LamMoi.getFont().getName(), Font.PLAIN, LamMoi.getFont().getSize()));
        LamMoi.setForeground(Color.BLACK);
    }//GEN-LAST:event_LamMoiMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LamMoi;
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> nam;
    private javax.swing.JComboBox<String> ngay;
    private javax.swing.JComboBox<String> thang;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
