/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.DangNhapDAO;
import DTO.INFO_TKNV;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Le Chuong
 */
public class PFQLNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form PFQLNhanVien
     */
    public PFQLNhanVien() {
        initComponents();
        setSize(1000, 545);
        //showTable();
        loadTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        btnThemTK = new javax.swing.JButton();
        btnSuaTK = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        btnSuaTK1 = new javax.swing.JButton();
        LamMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(992, 499));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nhập mã nhân viên");

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên Nhân Viên", "Giới tính", "Ngày Sinh", "Địa chỉ", "CCCD", "SDT", "Chức vụ"
            }
        ));
        jScrollPane1.setViewportView(TableNhanVien);

        btnThemTK.setBackground(new java.awt.Color(102, 102, 255));
        btnThemTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemTK.setText("Thêm nhân viên");
        btnThemTK.setBorder(null);
        btnThemTK.setBorderPainted(false);
        btnThemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemTK.setFocusPainted(false);
        btnThemTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemTKMouseExited(evt);
            }
        });
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        btnSuaTK.setBackground(new java.awt.Color(102, 102, 255));
        btnSuaTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaTK.setText("Chỉnh sửa thông tin nhân viên");
        btnSuaTK.setBorder(null);
        btnSuaTK.setBorderPainted(false);
        btnSuaTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaTK.setFocusPainted(false);
        btnSuaTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaTKMouseExited(evt);
            }
        });
        btnSuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTKActionPerformed(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimkiem.setForeground(new java.awt.Color(153, 153, 153));
        txtTimkiem.setText("Nhập mã NV...");
        txtTimkiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimkiemFocusGained(evt);
            }
        });
        txtTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimkiemMouseClicked(evt);
            }
        });
        txtTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimkiemKeyPressed(evt);
            }
        });

        btnTimkiem.setBackground(new java.awt.Color(102, 102, 255));
        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseExited(evt);
            }
        });
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnSuaTK1.setBackground(new java.awt.Color(102, 102, 255));
        btnSuaTK1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaTK1.setText("Quản lí tài khoản");
        btnSuaTK1.setBorder(null);
        btnSuaTK1.setBorderPainted(false);
        btnSuaTK1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaTK1.setFocusPainted(false);
        btnSuaTK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaTK1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaTK1MouseExited(evt);
            }
        });
        btnSuaTK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTK1ActionPerformed(evt);
            }
        });

        LamMoi.setBackground(new java.awt.Color(102, 102, 255));
        LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LamMoi.setText("Làm mới");
        LamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LamMoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LamMoiMouseExited(evt);
            }
        });
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btnSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimkiem)
                                .addGap(46, 46, 46)
                                .addComponent(LamMoi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnSuaTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
        txtTimkiem.setText("Nhập tài khoản...");
        txtTimkiem.setForeground(new Color(153, 153, 153));
        loadTabel();
    }//GEN-LAST:event_LamMoiActionPerformed

    private void LamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LamMoiMouseClicked

    private void btnSuaTK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTK1ActionPerformed
        // TODO add your handling code here:
        new FQuanLyTKNV().setVisible(true);
    }//GEN-LAST:event_btnSuaTK1ActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[10];
        String manv = txtTimkiem.getText();
        DangNhapDAO dn = new DangNhapDAO();
        if (txtTimkiem.getText().contains("Nhập mã NV...") == true) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
        } else if (txtTimkiem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
            txtTimkiem.setText("Nhập mã NV...");
            txtTimkiem.setForeground(new Color(153, 153, 153));
        } else {
            INFO_TKNV nx=dn.tableInfo2(manv);
            if (nx!=null){
                loadTabel2(nx);
            }
            else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên");
                txtTimkiem.setText("Nhập tài khoản...");
                txtTimkiem.setForeground(new Color(153, 153, 153));
                loadTabel();
            }
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimkiemMouseClicked

    private void txtTimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimkiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
            Object[] row = new Object[10];
            String manv = txtTimkiem.getText();
            DangNhapDAO dn = new DangNhapDAO();
            if (txtTimkiem.getText().contains("Nhập mã NV...") == true) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
            } else if (txtTimkiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm");
                txtTimkiem.setText("Nhập mã NV...");
                txtTimkiem.setForeground(new Color(153, 153, 153));
            } else {
                INFO_TKNV nx=dn.tableInfo2(manv);
                if (nx!=null){
                    loadTabel2(nx);
                }
                else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên");
                    txtTimkiem.setText("Nhập tài khoản...");
                    txtTimkiem.setForeground(new Color(153, 153, 153));
                    loadTabel();
                }
            }
         }
    }//GEN-LAST:event_txtTimkiemKeyPressed

    private void txtTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimkiemMouseClicked
        txtTimkiem.setText("");
        txtTimkiem.setForeground(Color.black);
    }//GEN-LAST:event_txtTimkiemMouseClicked

    private void txtTimkiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimkiemFocusGained

    }//GEN-LAST:event_txtTimkiemFocusGained

    private void btnSuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTKActionPerformed
        // TODO add your handling code here:
        new FCapNhatNV().setVisible(true);
    }//GEN-LAST:event_btnSuaTKActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        new FThemNV().setVisible(true);

    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnThemTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemTKMouseEntered
        // TODO add your handling code here:
        btnThemTK.setFont(new Font(btnThemTK.getFont().getName(), Font.BOLD, btnThemTK.getFont().getSize()));
        btnThemTK.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnThemTKMouseEntered

    private void btnThemTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemTKMouseExited
        // TODO add your handling code here:
        
        btnThemTK.setFont(new Font(btnThemTK.getFont().getName(), Font.PLAIN, btnThemTK.getFont().getSize()));
        btnThemTK.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnThemTKMouseExited

    private void btnSuaTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaTKMouseEntered
        // TODO add your handling code here:
        btnSuaTK.setFont(new Font(btnSuaTK.getFont().getName(), Font.BOLD, btnSuaTK.getFont().getSize()));
        btnSuaTK.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSuaTKMouseEntered

    private void btnSuaTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaTKMouseExited
        // TODO add your handling code here:
        
        btnSuaTK.setFont(new Font(btnSuaTK.getFont().getName(), Font.PLAIN, btnSuaTK.getFont().getSize()));
        btnSuaTK.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnSuaTKMouseExited

    private void btnSuaTK1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaTK1MouseEntered
        // TODO add your handling code here:
        
        btnSuaTK1.setFont(new Font(btnSuaTK1.getFont().getName(), Font.BOLD, btnSuaTK1.getFont().getSize()));
        btnSuaTK1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSuaTK1MouseEntered

    private void btnSuaTK1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaTK1MouseExited
        // TODO add your handling code here:
        
        btnSuaTK1.setFont(new Font(btnSuaTK1.getFont().getName(), Font.PLAIN, btnSuaTK1.getFont().getSize()));
        btnSuaTK1.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnSuaTK1MouseExited

    private void btnTimkiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseEntered
        // TODO add your handling code here:
        
        btnTimkiem.setFont(new Font(btnTimkiem.getFont().getName(), Font.BOLD, btnTimkiem.getFont().getSize()));
        btnTimkiem.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnTimkiemMouseEntered

    private void btnTimkiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseExited
        // TODO add your handling code here:
        
        btnTimkiem.setFont(new Font(btnTimkiem.getFont().getName(), Font.PLAIN, btnTimkiem.getFont().getSize()));
        btnTimkiem.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnTimkiemMouseExited

    private void LamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseEntered
        // TODO add your handling code here:
        
        LamMoi.setFont(new Font(LamMoi.getFont().getName(), Font.BOLD, LamMoi.getFont().getSize()));
        LamMoi.setForeground(Color.WHITE);
    }//GEN-LAST:event_LamMoiMouseEntered

    private void LamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseExited
        // TODO add your handling code here:
        
        LamMoi.setFont(new Font(LamMoi.getFont().getName(), Font.PLAIN, LamMoi.getFont().getSize()));
        LamMoi.setForeground(Color.BLACK);
    }//GEN-LAST:event_LamMoiMouseExited

    public void loadTabel() {
        ArrayList<INFO_TKNV> list = DangNhapDAO.tableInfo();
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[9];
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getMaNV();
            row[1] = list.get(i).getHoTen();
            row[2] = list.get(i).getGt();
            row[3] = list.get(i).getNgaySinh();
            row[4] = list.get(i).getDC();
            row[5] = list.get(i).getCCCD();
            row[6] = list.get(i).getSDT();
            row[7] = list.get(i).getChucVu();
            tblModel.addRow(row);
        }
    }
    
    public void loadTabel2(INFO_TKNV nx) {
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[10];
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        row[0] = nx.getMaNV();
        row[1] = nx.getHoTen();
        row[2] = nx.getGt();
        row[3] = nx.getNgaySinh();
        row[4] = nx.getDC();
        row[5] = nx.getCCCD();
        row[6] = nx.getSDT();
        row[7] = nx.getChucVu();
        tblModel.addRow(row);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LamMoi;
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JButton btnSuaTK;
    private javax.swing.JButton btnSuaTK1;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
