/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.LichLamViecDAO;
import DAO.NhapXeDAO;
import DTO.NhapXeDTO;
import DTO.lichlamviec;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PFXemLichLam extends javax.swing.JPanel {
    private String ma;

    /**
     * Creates new form PFReceiveCar
     */
    public PFXemLichLam(String maNV) {
        initComponents();
        setSize(1270, 720);
        ma=maNV;
        loadTable1();
    }

    public boolean isLeapYear(int year) {
        return (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
    }
    
    public int getDaysOfMonth(int month,int year) {
        // Tháng 2 có thể có 28 hoặc 29 ngày
        if (month == Month.FEBRUARY.getValue()) {
             if(isLeapYear(year)){
                 return 29;
             }else return 28;
        // Các tháng 4, 6, 9, 11 có 30 ngày
        } else if (month == Month.APRIL.getValue() || month == Month.JUNE.getValue() ||
                   month == Month.SEPTEMBER.getValue() || month == Month.NOVEMBER.getValue()) {
            return 30;
          // Các tháng còn lại có 31 ngày
        }else return 31;
    }
    
    public void loadTable1() {
        ArrayList<lichlamviec> list = LichLamViecDAO.xemCaLam1(ma);
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNgay();
            row[1] = list.get(i).getTenCa();
            row[2] = list.get(i).getGioBatDau();
            row[3] = list.get(i).getGioKetThuc();
            tblModel.addRow(row);
        }
     }

public void loadTable2(String tuNgay, String denNgay) {
        ArrayList<lichlamviec> list = LichLamViecDAO.xemCaLam2(ma,tuNgay, denNgay);
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
                tblModel.removeRow(i);
        }
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNgay();
            row[1] = list.get(i).getTenCa();
            row[2] = list.get(i).getGioBatDau();
            row[3] = list.get(i).getGioKetThuc();
            tblModel.addRow(row);
        }
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        XEM = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ngay = new javax.swing.JComboBox<>();
        thang = new javax.swing.JComboBox<>();
        nam = new javax.swing.JComboBox<>();
        ngay2 = new javax.swing.JComboBox<>();
        thang2 = new javax.swing.JComboBox<>();
        nam2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1004, 487));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Xem ca làm việc:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Từ ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Đến ");

        XEM.setBackground(new java.awt.Color(102, 102, 255));
        XEM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        XEM.setText("XEM");
        XEM.setBorder(null);
        XEM.setBorderPainted(false);
        XEM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XEM.setName("XEM"); // NOI18N
        XEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XEMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XEMMouseExited(evt);
            }
        });
        XEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XEMActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Ca Làm Việc");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày ", "Tên ca", "Giờ bắt đầu", "Giờ kết thúc"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Ngày");

        jLabel5.setText("Tháng");

        jLabel6.setText("Năm");

        ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                thangItemStateChanged(evt);
            }
        });

        nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        nam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namItemStateChanged(evt);
            }
        });

        ngay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        thang2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thang2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                thang2ItemStateChanged(evt);
            }
        });

        nam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        nam2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nam2ItemStateChanged(evt);
            }
        });

        jLabel7.setText("Ngày");

        jLabel8.setText("Tháng");

        jLabel9.setText("Năm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(jLabel3)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel5)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ngay2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thang2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel7)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel8)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel9)))
                                .addGap(18, 18, 18)
                                .addComponent(XEM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(ngay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(XEM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

     
    private void XEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XEMActionPerformed
        String tuNgay=(String)nam.getSelectedItem()+"-"+(String)thang.getSelectedItem()+"-"+(String)ngay.getSelectedItem();
        String denNgay=(String)nam2.getSelectedItem()+"-"+(String)thang2.getSelectedItem()+"-"+(String)ngay2.getSelectedItem();
        loadTable2(tuNgay,denNgay);
    }//GEN-LAST:event_XEMActionPerformed

    private void thangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_thangItemStateChanged
        // TODO add your handling code here:
        int Month=Integer.parseInt(thang.getSelectedItem().toString());
        int Year= Integer.parseInt(nam.getSelectedItem().toString());
        int Ngay=getDaysOfMonth(Month, Year);
        ngay.removeAllItems();
        for (int i = 1; i <= Ngay; i++) {
            ngay.addItem(String.valueOf(i));   
        }
    }//GEN-LAST:event_thangItemStateChanged

    private void thang2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_thang2ItemStateChanged
        // TODO add your handling code here:
        int Month=Integer.parseInt(thang2.getSelectedItem().toString());
        int Year= Integer.parseInt(nam2.getSelectedItem().toString());
        int Ngay=getDaysOfMonth(Month, Year);
        ngay2.removeAllItems();
        for (int i = 1; i <= Ngay; i++) {
            ngay2.addItem(String.valueOf(i));   
        }
    }//GEN-LAST:event_thang2ItemStateChanged

    private void namItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namItemStateChanged
        // TODO add your handling code here:
        int Month=Integer.parseInt(thang.getSelectedItem().toString());
        int Year= Integer.parseInt(nam.getSelectedItem().toString());
        int Ngay=getDaysOfMonth(Month, Year);
        ngay.removeAllItems();
        for (int i = 1; i <= Ngay; i++) {
            ngay.addItem(String.valueOf(i));   
        }
    }//GEN-LAST:event_namItemStateChanged

    private void nam2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nam2ItemStateChanged
        // TODO add your handling code here:
        int Month=Integer.parseInt(thang2.getSelectedItem().toString());
        int Year= Integer.parseInt(nam2.getSelectedItem().toString());
        int Ngay=getDaysOfMonth(Month, Year);
        ngay2.removeAllItems();
        for (int i = 1; i <= Ngay; i++) {
            ngay2.addItem(String.valueOf(i));   
        }
    }//GEN-LAST:event_nam2ItemStateChanged

    private void XEMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XEMMouseEntered
        // TODO add your handling code here:
        XEM.setFont(new Font(XEM.getFont().getName(), Font.BOLD, XEM.getFont().getSize()));
        XEM.setForeground(Color.WHITE);
    }//GEN-LAST:event_XEMMouseEntered

    private void XEMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XEMMouseExited
        // TODO add your handling code here:
        XEM.setFont(new Font(XEM.getFont().getName(), Font.PLAIN, XEM.getFont().getSize()));
        XEM.setForeground(Color.BLACK);
    }//GEN-LAST:event_XEMMouseExited


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XEM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> nam;
    private javax.swing.JComboBox<String> nam2;
    private javax.swing.JComboBox<String> ngay;
    private javax.swing.JComboBox<String> ngay2;
    private javax.swing.JComboBox<String> thang;
    private javax.swing.JComboBox<String> thang2;
    // End of variables declaration//GEN-END:variables
}
